# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
pr:
- none
 
stages:
- stage: Build
  displayName: 'Build'
 
  jobs:
  - job: BuildAndPublish
 
    pool:
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: 'Release'

 
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
 
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
 
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'
 
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    - task: AzureFunctionApp@2
      inputs:
        connectedServiceNameARM: 'Free Trial(c76f3d6d-37b1-42f2-b26c-88cd0317d3ec)'
        appType: 'functionApp'
        appName: 'demofcnapp'
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        deploymentMethod: 'auto'
