trigger:
- none
 
stages:
- stage: Build
  displayName: 'Build'
 
  jobs:
  - job: BuildAndPublish
 
    pool:
      vmImage: ubuntu-latest
    variables:
      buildConfiguration: 'Release'

 
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
 
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
 
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'
 
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
- stage: Deploy
  displayName: 'Deploy the application'    

  jobs:
  - job: Deploy
 
    pool:
      vmImage: ubuntu-latest
    
    steps:
    
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(1)(c76f3d6d-37b1-42f2-b26c-88cd0317d3ec)'
        appType: 'webApp'
        WebAppName: 'haseendemoappv'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'